package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static cloud.autotests.helpers.DriverHelper.getConsoleLogs;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("should be valid message")
    void generatedTest() {
        step("Open 'https://github.com/login'", () -> {
            // todo just add selenium action
        });

        step("Set username 'Alex'", () -> {
            // todo just add selenium action
        });

        step("Set password '1111'", () -> {
            // todo just add selenium action
        });

        step("Submit form", () -> {
            // todo just add selenium action
        });

        step("Verify successful message present", () -> {
            // todo just add selenium action
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...' and the page has 'title' tag")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://github.com/login'", () ->
            open("https://github.com/login"));

        step("Page title should have text 'Sign in to GitHub · GitHub'", () -> {
            String expectedTitle = "Sign in to GitHub · GitHub";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated, because test steps contain text 'http...'")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://github.com/login'", () ->
            open("https://github.com/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}